### ISSUE TITLE
age doesn't increase when successionTimeStep is 1

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/Biomass_core#41]
In this scenario, we skip the reclassification of ages, but forget to add 1 to age

**Comment by CeresBarros** [comment]
@ianmseddy is this still an issue? @eliotmcintire do the recently revived tests detect this somehow ?

**Comment by ianmseddy** [comment]
Hmm.... I'm not sure. I suspect we fixed it, but I will confirm on Monday.
