### ISSUE TITLE
error in plotSummaryBySpecies assertions

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Biomass_core#73]
the following fails because `cols` is undefined in `plotSummaryBySpecies`:

```r
assertSppVectors(sppEquiv = sim$sppEquiv, sppEquivCol = P(sim)$sppEquivCol,
                   sppColorVect = cols2)
```

need to identify where this object should be coming from and ensure it's available for use in this function

-----

`assertSppVectors` done here:

https://github.com/PredictiveEcology/Biomass_core/blob/development/Biomass_core.R#L1646-L1647

but I see an object called `cols2` not defined until further down:

https://github.com/PredictiveEcology/Biomass_core/blob/development/Biomass_core.R#L1716-L1717

**Comment by achubaty** [comment]
@CeresBarros can we chat about this when you have a few mins to spare?

**Comment by CeresBarros** [comment]
I'm not hitting this witht he LandR Publication sims... I'll take a closer look

**Comment by CeresBarros** [comment]
@achubaty what branch are you looking at?

**Comment by achubaty** [comment]
I'm using `development` (linked above). I moved that assertion into the block where cols2 actually gets created, and am testing before pushing this fix

**Comment by CeresBarros** [comment]
I think we need to `assert` twice, where you moved the block to and early (where it was at the start) but with `sim$sppColorsVect` instead of `cols2`
